In [1]:
with open('mat.txt') as f:
    import numpy as np
    lines = f.readlines()
    m0,n0 = np.array(lines[0].split(),dtype = np.int)  #矩阵A 的行列
    A = np.zeros((m0,n0),dtype = np.float)
    for i,j in enumerate(range(1,m0+1,1)):
        A[i] = np.array(lines[j].split(),dtype = np.float)
    print(A)
    m1,n1 = np.array(lines[1+m0].split(),dtype = np.int)  #矩阵B 的行列
    B = np.zeros((m1,n1),dtype = np.float)
    for i,j in enumerate(range(m0+2,m0+m1+2,1)):
        B[i] = np.array(lines[j].split(),dtype = np.float)
    print(B)
    if (n0!=m1):
        raise ValueError("不满足矩阵乘法要求")
    else:
        C = np.zeros((m0,n1),dtype = np.int)
        for i in range(m0):
            for j in range(n1):
                for k in range(m1):
                    C[i,j] += A[i,k]*B[k,j]
        print(C)
        

[[1. 2. 3.]
 [2. 3. 4.]]
[[3. 4.]
 [4. 5.]
 [5. 6.]]
[[26 32]
 [38 47]]
