## 用numpy输入数据并计算人均GDP

In [10]:
import numpy as np
data = np.loadtxt("data.csv",encoding='utf-8',delimiter=",",dtype=object)
print(data)
GDP = np.array(data[1:,2],dtype="float")
population = np.array(data[1:,1],dtype="float")
print("\n\n各省份人均GDP:\n",np.c_[data[1:,0],GDP/population])

[['省' '人口(万人)' 'GDP(亿元)' '电力消耗(亿千瓦小时)' '土地面积(万平方千米)']
 ['北京市' '2154' '30319.98' '1142.38' '1.68']
 ['天津市' '1560' '18809.64' '861.44' '1.13']
 ['河北省' '7556' '36010.27' '3665.66' '18.77']
 ['山西省' '3718' '16818.11' '2160.53' '15.63']
 ['内蒙古自治区' '2534' '17289.22' '3353.44' '118.3']
 ['辽宁省' '4359' '25315.35' '2302.38' '14.59']
 ['吉林省' '2704' '15074.62' '750.57' '18.74']
 ['黑龙江省' '3773' '16361.62' '973.88' '45.48']
 ['上海市' '2424' '32679.87' '1566.66' '0.63']
 ['江苏省' '8051' '92595.40' '6128.27' '10.26']
 ['浙江省' '5737' '56197.15' '4532.82' '10.2']
 ['安徽省' '6324' '30006.82' '2135.07' '13.97']
 ['福建省' '3941' '35804.04' '2313.82' '12.13']
 ['江西省' '4648' '21984.78' '1428.77' '16.7']
 ['山东省' '10047' '76469.67' '5916.77' '15.38']
 ['河南省' '9605' '48055.86' '3417.68' '16.7']
 ['湖北省' '5917' '39366.55' '2071.43' '18.59']
 ['湖南省' '6899' '36425.78' '1745.24' '21.18']
 ['广东省' '11346' '97277.77' '6323.35' '18']
 ['广西壮族自治区' '4926' '20352.51' '1702.75' '23.6']
 ['海南省' '934' '4832.05' '326.78' '3.4']
 ['重庆市' '

In [25]:
a = np.empty((4,5))
for i in range(1,5):
    a = np.array(data[i][1:],dtype=np.float)
    print(a)
#np.array(data[2][1:],dtype=np.float)

[2.154000e+03 3.031998e+04 1.142380e+03 1.680000e+00]
[1.560000e+03 1.880964e+04 8.614400e+02 1.130000e+00]
[7.556000e+03 3.601027e+04 3.665660e+03 1.877000e+01]
[3.718000e+03 1.681811e+04 2.160530e+03 1.563000e+01]


# 用pandas输入数据

In [3]:
import pandas as pd
a=pd.read_csv("data.csv",index_col='省')
a

人口(万人)   GDP(亿元)  电力消耗(亿千瓦小时)  土地面积(万平方千米)
省                                                   
北京市         2154  30319.98      1142.38         1.68
天津市         1560  18809.64       861.44         1.13
河北省         7556  36010.27      3665.66        18.77
山西省         3718  16818.11      2160.53        15.63
内蒙古自治区      2534  17289.22      3353.44       118.30
辽宁省         4359  25315.35      2302.38        14.59
吉林省         2704  15074.62       750.57        18.74
黑龙江省        3773  16361.62       973.88        45.48
上海市         2424  32679.87      1566.66         0.63
江苏省         8051  92595.40      6128.27        10.26
浙江省         5737  56197.15      4532.82        10.20
安徽省         6324  30006.82      2135.07        13.97
福建省         3941  35804.04      2313.82        12.13
江西省         4648  21984.78      1428.77        16.70
山东省        10047  76469.67      5916.77        15.38
河南省         9605  48055.86      3417.68        16.70
湖北省         5917  39366.55      2071.43        18.59
湖南省         6899  36425.78      1745.24        21.18
广东省        11346  97277.77      6323.35        18.00
广西壮族自治区     4926  20352.51      1702.75        23.60
海南省          934   4832.05       326.78         3.40
重庆市         3102  20363.19      1114.47         8.23
四川省         8341  40678.13      2459.49        48.14
贵州省         3600  14806.45      1482.12        17.60
云南省         4830  17881.12      1679.08        38.33
西藏自治区        344   1477.63        69.02       122.80
陕西省         3864  24438.32      1594.17        20.56
甘肃省         2637   8246.07      1289.52        45.44
青海省          603   2865.23       738.34        72.23
宁夏回族自治区      688   3705.18      1064.85         6.64
新疆维吾尔自治区    2487  12199.08      2138.33       166.00

In [ ]:
a1=a.stack()
a1

### 列索引为主，计算综合

In [ ]:
sum(a['人口(万人)'])

In [ ]:
a1.index.names=['省','数据']
a1